"""add grid_id to outbreak

Revision ID: 12684fe24aab
Revises: 39d92bf029fb
Create Date: 2026-09-25 18:15:16.177392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12684fe24aab'
down_revision: Union[str, Sequence[str], None] = '39d92bf029fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbreaks', sa.Column('grid_id', sa.String(), nullable=True))
    op.create_index('uq_active_outbreak', 'outbreaks', ['disease', 'grid_id'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_outbreak', table_name='outbreaks', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
    op.drop_column('outbreaks', 'grid_id')
    # ### end Alembic commands ###
