"""add indexes

Revision ID: 39d92bf029fb
Revises: 98d58371273f
Create Date: 2026-09-25 13:36:17.753202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d92bf029fb'
down_revision: Union[str, Sequence[str], None] = '98d58371273f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_advisories_crop'), 'advisories', ['crop'], unique=False)
    op.create_index(op.f('ix_advisories_timestamp'), 'advisories', ['timestamp'], unique=False)
    op.create_index(op.f('ix_diagnoses_crop'), 'diagnoses', ['crop'], unique=False)
    op.create_index(op.f('ix_diagnoses_disease'), 'diagnoses', ['disease'], unique=False)
    op.create_index(op.f('ix_diagnoses_timestamp'), 'diagnoses', ['timestamp'], unique=False)
    op.create_index(op.f('ix_federation_signals_affected_crop'), 'federation_signals', ['affected_crop'], unique=False)
    op.create_index(op.f('ix_federation_signals_timestamp'), 'federation_signals', ['timestamp'], unique=False)
    op.create_index(op.f('ix_outbreaks_disease'), 'outbreaks', ['disease'], unique=False)
    op.create_index(op.f('ix_outbreaks_timestamp'), 'outbreaks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbreaks_timestamp'), table_name='outbreaks')
    op.drop_index(op.f('ix_outbreaks_disease'), table_name='outbreaks')
    op.drop_index(op.f('ix_federation_signals_timestamp'), table_name='federation_signals')
    op.drop_index(op.f('ix_federation_signals_affected_crop'), table_name='federation_signals')
    op.drop_index(op.f('ix_diagnoses_timestamp'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_disease'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_crop'), table_name='diagnoses')
    op.drop_index(op.f('ix_advisories_timestamp'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_crop'), table_name='advisories')
    # ### end Alembic commands ###
