"""add outbreak status

Revision ID: cb173cba2f09
Revises: ec25f1d991bb
Create Date: 2026-09-25 13:33:31.847277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb173cba2f09'
down_revision: Union[str, Sequence[str], None] = 'ec25f1d991bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbreaks', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbreaks', 'status')
    # ### end Alembic commands ###
